import MemberPointUsageListPage from './MemberPointUsageListPage.vue'
import MemberPointUsageCustomerListPage from './MemberPointUsageCustomerListPage.vue'
import MemberPointAllocationSpecifyInBulkPage from './MemberPointAllocationSpecifyInBulkPage.vue'
import MemberPointUsageRegistrationBulkPage from './MemberPointUsageRegistrationBulkPage.vue'

export { MemberPointUsageListPage, MemberPointUsageCustomerListPage, MemberPointAllocationSpecifyInBulkPage, MemberPointUsageRegistrationBulkPage }
