import ProductDiscountPromotionListPage from './ProductDiscountPromotionListPage.vue'
import ProductDiscountPromotionRegistrationPage from './ProductDiscountPromotionRegistrationPage.vue'

export { ProductDiscountPromotionListPage, ProductDiscountPromotionRegistrationPage }
